### ISSUE TITLE
bbn-cycle issues

### ISSUE THREAD

**Issue by bouzuya** [bouzuya/mr-jums#2]
- [x] bouzuya/bbn-cycle#18 CSS for TB
- [x] bouzuya/bbn-cycle#17 nav design
- [x] bouzuya/bbn-cycle#15 browser back
- [x] bouzuya/bbn-cycle#14 no js
- [x] bouzuya/bbn-cycle#11 shortcut keys
- [x] bouzuya/bbn-cycle#10 pre-rendering
- [x] bouzuya/bbn-cycle#7 search entries (tag:)
- [x] bouzuya/bbn-cycle#6 search entries (title)
- [x] bouzuya/bbn-cycle#5 CSS for SP
- [x] bouzuya/bbn-cycle#4 CSS for PC

**Comment by bouzuya** [comment]
sizes (chrome develer tool)
- mobile s: 320px
- mobile m: 375px
- mobile l: 425px
- tablet: 768px
- laptop: 1024px
- laptop: 1440px
- 4k: 2560px

**Comment by bouzuya** [comment]
https://github.com/bouzuya/mr-jums/commit/dd513bd096351ef6082197f00694fc7fb2d6f29b

viewport:

- [x] mobile
- [ ] tablet
- [ ] laptop

**Comment by bouzuya** [comment]
nav 適宜対応しているので close

**Comment by bouzuya** [comment]
bouzuya/bbn-cycle#7 は #40 で拾うので close

**Comment by bouzuya** [comment]
bouzuya/bbn-cycle#6 は #41 で拾うので close

**Comment by bouzuya** [comment]
bouzuya/bbn-cycle#15 はまだバグがあるものの対応したので close

**Comment by bouzuya** [comment]
bouzuya/bbn-cycle#14 は #57 で対応するので close

**Comment by bouzuya** [comment]
bouzuya/bbn-cycle#11 は #58 で対応するので close

**Comment by bouzuya** [comment]
bouzuya/bbn-cycle#10 は #59 で対応するので close
